schema = 2
distribution = "dj-orm"
application = "tree-delta"
yapc_commit = "df3a78fefc78ffb304dd5a32196e1be7a430bbcb"
upstream_remote = "upstream"
upstream_url = "https://github.com/django/django.git"
upstream_ref = "5.2.11-9-g703777cbbc"
upstream_series = "5.2"
lts_series = ["5.2", "6.2"]
upstream_base_commit = "703777cbbc268f62083c703fa27fa582b54bcc93"
release_revision = 0
