schema = 1
upstream_ref = "5.2.17"
upstream_commit = "e802ada38b3ecf345915163bb6d7f008be411664"

[djrm]
max_byte_differences = 191
max_raw_ast_differences = 32
max_non_ast_byte_differences = 159
upstream_only = 2956
upstream_only_sha256 = "408a4f641d5c50f133c950ab9077d751889d52a067055e44c87d345ca6e04266"
fork_only = 5
fork_only_sha256 = "8e6505cb07acd8f7b72ea7142ed6e0ca045269ab22d2538463282818fa7770c9"
executable_ast_differences = [
  "djrm/__init__.py",
  "djrm/conf/__init__.py",
  "djrm/contrib/postgres/fields/array.py",
  "djrm/contrib/postgres/fields/hstore.py",
  "djrm/contrib/postgres/fields/ranges.py",
  "djrm/contrib/postgres/operations.py",
  "djrm/core/checks/__init__.py",
  "djrm/core/management/__init__.py",
  "djrm/db/backends/base/creation.py",
  "djrm/db/backends/base/operations.py",
  "djrm/db/backends/mysql/features.py",
  "djrm/db/backends/oracle/features.py",
  "djrm/db/backends/sqlite3/creation.py",
  "djrm/db/backends/sqlite3/features.py",
  "djrm/db/models/base.py",
  "djrm/db/models/fields/__init__.py",
  "djrm/db/models/fields/files.py",
  "djrm/db/models/fields/json.py",
  "djrm/db/models/fields/related.py",
  "djrm/db/models/functions/math.py",
  "djrm/db/models/sql/compiler.py",
  "djrm/test/__init__.py",
  "djrm/test/runner.py",
  "djrm/test/signals.py",
  "djrm/test/testcases.py",
  "djrm/test/utils.py",
  "djrm/utils/log.py",
  "djrm/utils/translation/__init__.py",
  "djrm/utils/translation/reloader.py",
  "djrm/utils/translation/template.py",
]

[tests]
max_byte_differences = 334
max_raw_ast_differences = 39
max_non_ast_byte_differences = 295
upstream_only = 1477
upstream_only_sha256 = "cf7d6f1ef57423d764b499d9cb9c6ddc68db61723beb475d72094135db8b5cff"
fork_only = 28
fork_only_sha256 = "3743224247dfd8841a84f89d099b2789cec117255008045d8d5eb72bf82cd184"
executable_ast_differences = [
  "tests/aggregation_regress/tests.py",
  "tests/apps/apps.py",
  "tests/apps/tests.py",
  "tests/backends/base/test_base.py",
  "tests/backends/base/test_creation.py",
  "tests/contenttypes_tests/models.py",
  "tests/contenttypes_tests/test_models.py",
  "tests/field_deconstruction/tests.py",
  "tests/file_storage/tests.py",
  "tests/fixtures/models.py",
  "tests/fixtures/tests.py",
  "tests/fixtures_regress/models.py",
  "tests/generic_relations_regress/tests.py",
  "tests/m2m_regress/models.py",
  "tests/m2m_through_regress/models.py",
  "tests/m2m_through_regress/tests.py",
  "tests/managers_regress/tests.py",
  "tests/model_enums/tests.py",
  "tests/model_fields/test_textfield.py",
  "tests/model_fields/tests.py",
  "tests/model_inheritance_regress/tests.py",
  "tests/postgres_tests/test_integration.py",
  "tests/prefetch_related/tests.py",
  "tests/proxy_models/tests.py",
  "tests/queries/tests.py",
  "tests/raw_query/tests.py",
  "tests/runtests.py",
  "tests/shell/tests.py",
  "tests/swappable_models/tests.py",
  "tests/test_runner/test_debug_sql.py",
  "tests/test_runner/test_discover_runner.py",
  "tests/test_runner/tests.py",
  "tests/test_sqlite.py",
  "tests/test_utils/tests.py",
  "tests/timezones/tests.py",
  "tests/utils_tests/test_html.py",
  "tests/utils_tests/test_module_loading.py",
  "tests/utils_tests/test_text.py",
]
