schema = 3
distribution = "djrm"
application = "tree-delta"
yapc_commit = "df3a78fefc78ffb304dd5a32196e1be7a430bbcb"
upstream_remote = "upstream"
upstream_url = "https://github.com/django/django.git"
upstream_ref = "5.2.17"
upstream_series = "5.2"
lts_version_majors = { "5.2" = 0, "6.2" = 1 }
upstream_base_commit = "e802ada38b3ecf345915163bb6d7f008be411664"
release_version = "0.1.3"
