[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "djo"
dynamic = ["version"]
requires-python = ">= 3.10"
dependencies = [
    "asgiref>=3.8.1",
    "sqlparse>=0.3.1",
    "tzdata; sys_platform == 'win32'",
]
authors = [
  {name = "djo contributors"},
]
description = "Django ORM, migrations, and database backends as a standalone library."
readme = "README.rst"
license = "BSD-3-Clause"
license-files = ["LICENSE", "LICENSE.python", "AUTHORS"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Database",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.optional-dependencies]
postgresql = ["psycopg>=3.1.8; python_version >= '3.10'", "psycopg2>=2.9"]
mysql = ["mysqlclient>=2.1"]

[project.scripts]
djo = "djo.core.management:execute_from_command_line"

[project.urls]
Source = "https://github.com/django/django"
Tracker = "https://github.com/django/django/issues"

[tool.black]
target-version = ["py310"]
force-exclude = "tests/test_runner_apps/tagged/tests_syntax_error.py"

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = "djo"

[tool.setuptools.dynamic]
version = {attr = "djo.__version__"}

[tool.setuptools.packages.find]
include = ["djo*"]
